/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DashboardPermissionObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type DashboardPermissionParameters struct {

	// ID of the dashboard to apply permissions to.
	// +kubebuilder:validation:Required
	DashboardID *int64 `json:"dashboardId" tf:"dashboard_id,omitempty"`

	// The permission items to add/update. Items that are omitted from the list will be removed.
	// +kubebuilder:validation:Required
	Permissions []PermissionsParameters `json:"permissions" tf:"permissions,omitempty"`
}

type PermissionsObservation struct {
}

type PermissionsParameters struct {

	// Permission to associate with item. Must be one of `View`, `Edit`, or `Admin`.
	// +kubebuilder:validation:Required
	Permission *string `json:"permission" tf:"permission,omitempty"`

	// Manage permissions for `Viewer` or `Editor` roles.
	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// ID of the team to manage permissions for.
	// +kubebuilder:validation:Optional
	TeamID *int64 `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// ID of the user to manage permissions for.
	// +kubebuilder:validation:Optional
	UserID *int64 `json:"userId,omitempty" tf:"user_id,omitempty"`
}

// DashboardPermissionSpec defines the desired state of DashboardPermission
type DashboardPermissionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DashboardPermissionParameters `json:"forProvider"`
}

// DashboardPermissionStatus defines the observed state of DashboardPermission.
type DashboardPermissionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DashboardPermissionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// DashboardPermission is the Schema for the DashboardPermissions API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,grafanajet}
type DashboardPermission struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DashboardPermissionSpec   `json:"spec"`
	Status            DashboardPermissionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DashboardPermissionList contains a list of DashboardPermissions
type DashboardPermissionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DashboardPermission `json:"items"`
}

// Repository type metadata.
var (
	DashboardPermission_Kind             = "DashboardPermission"
	DashboardPermission_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DashboardPermission_Kind}.String()
	DashboardPermission_KindAPIVersion   = DashboardPermission_Kind + "." + CRDGroupVersion.String()
	DashboardPermission_GroupVersionKind = CRDGroupVersion.WithKind(DashboardPermission_Kind)
)

func init() {
	SchemeBuilder.Register(&DashboardPermission{}, &DashboardPermissionList{})
}
